name: docker hub deploy test

on:
  push:
    branches: main
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER_SECRET }}
          password: ${{ secrets.DOCKERHUB_TOKEN_SECRET }}
 
